# Generated by Django 5.1 on 2024-08-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('kg', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('debt', models.BooleanField(default=False)),
                ('give', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
            ],
        ),
    ]
