# Generated by Django 5.1 on 2024-08-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopApp', '0002_orders_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Zakazlar', 'verbose_name_plural': 'Zakazlar'},
        ),
    ]
